#+AUTHOR: Marcio Woitek
#+TITLE: Held-Karp Algorithm
#+DATE:
#+LATEX_HEADER: \usepackage[a4paper,left=1cm,right=1cm,top=1cm,bottom=1cm]{geometry}
#+LATEX_HEADER: \usepackage[american]{babel}
#+LATEX_HEADER: \usepackage[sc]{mathpazo}
#+LATEX_HEADER: \linespread{1.05}
#+LATEX_HEADER: \setlength\parindent{0pt}
#+LATEX_HEADER: \newcommand{\minCostPath}[2]{\mathrm{minCostPath}\left(\left\{#1\right\},#2\right)}
#+LATEX_HEADER: \newcommand{\minCostTour}[2]{\mathrm{minCostTour}\left(\left\{#1\right\},#2\right)}
#+OPTIONS: toc:nil
#+STARTUP: hideblocks

#+BEGIN_SRC latex
\thispagestyle{empty}
\pagestyle{empty}
#+END_SRC

All problems are related to the graph shown below. Black edges have weight 1,
and red edges have weight 2.
#+BEGIN_SRC latex
\begin{figure}[h]
  \centering
  \includegraphics[scale=0.25]{held_karp_graph.jpeg}
  \caption{TSP instance}
\end{figure}
#+END_SRC

* Problem 1
:PROPERTIES:
:UNNUMBERED: notoc
:END:

\begin{equation}
\minCostPath{2,3}{4}=\min\left(\minCostPath{2}{3}+C_{3,4},\minCostPath{3}{2}+C_{2,4}\right)
\end{equation}

* Problem 2
:PROPERTIES:
:UNNUMBERED: notoc
:END:

We begin by computing the arguments of the $\min$ function on the RHS of the above equation:
\begin{align*}
\minCostPath{2}{3}+C_{3,4}&=C_{1,2}+C_{2,3}+C_{3,4}=2+1+1=4,\\
\minCostPath{3}{2}+C_{2,4}&=C_{1,3}+C_{3,2}+C_{2,4}=1+1+1=3.
\end{align*}
Hence:
\begin{equation}
\minCostPath{2,3}{4}=\min(4,3)=3.
\end{equation}

* Problem 3
:PROPERTIES:
:UNNUMBERED: notoc
:END:

I believe the correct answer is vertex 2. After all, from the above
calculations, visiting vertex 2 before vertex 4 yields the optimal solution.
However, the answer that is accepted as correct is *vertex 3*. Perhaps I'm
wrong. But it wouldn't be the first instructor mistake I catch.

* Problem 4
:PROPERTIES:
:UNNUMBERED: notoc
:END:

The correct formula for the recurrence is
\begin{equation}
\mathrm{minCostTSPTour}(C)=\min
  \begin{cases}
    \minCostTour{2,3,5}{4}+C_{4,1}\\
    \minCostTour{2,3,4}{5}+C_{5,1}\\
    \minCostTour{3,4,5}{2}+C_{2,1}\\
    \minCostTour{2,4,5}{3}+C_{3,1}
  \end{cases}
.
\end{equation}
Therefore, the missing portions are given by
\begin{align}
??_1&=C_{4,1}=2,\\
??_2&=C_{5,1}=1,\\
??_3&=2,\\
??_4&=C_{2,1}=2,\\
??_5&=\{2,4,5\},\\
??_6&=C_{3,1}=1.
\end{align}
