#+AUTHOR: Marcio Woitek
#+TITLE: TSP Basics
#+DATE:
#+LATEX_HEADER: \usepackage[a4paper,left=1cm,right=1cm,top=1cm,bottom=1cm]{geometry}
#+LATEX_HEADER: \usepackage[american]{babel}
#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage[sc]{mathpazo}
#+LATEX_HEADER: \linespread{1.05}
#+LATEX_HEADER: \renewcommand{\labelitemi}{$\rhd$}
#+LATEX_HEADER: \setlength\parindent{0pt}
#+LATEX_HEADER: \setlist[itemize]{leftmargin=*}
#+LATEX_HEADER: \setlist{nosep}
#+OPTIONS: toc:nil
#+STARTUP: hideblocks

#+BEGIN_SRC latex
\thispagestyle{empty}
\pagestyle{empty}
#+END_SRC

Problems 1 and 2 are related to the graph below. Black edges have weight 1, and
red edges have weight 2.
#+BEGIN_SRC latex
\begin{figure}[H]
  \centering
  \includegraphics[scale=0.15]{held_karp_graph.jpeg}
  \caption{TSP instance}
\end{figure}
#+END_SRC

* Problem 1
:PROPERTIES:
:UNNUMBERED: notoc
:END:

- There is a TSP tour whose cost is 5, i.e., it involves only the black edges in
  the graph.
- The sequence of vertices 1, 2, 3, 4, 5, 1 (1 is the start/end point) is a
  valid TSP tour of cost 6.

* Problem 2
:PROPERTIES:
:UNNUMBERED: notoc
:END:

*Answer: True*

* Problem 3
:PROPERTIES:
:UNNUMBERED: notoc
:END:

This problem is related to the following graph:
#+BEGIN_SRC latex
\begin{figure}[H]
  \centering
  \includegraphics[scale=0.2]{ham_cycle.jpeg}
  \caption{Graph for question on Hamiltonian cycles}
\end{figure}
#+END_SRC
- The reduction will need to assign a weight of 1 to each edge in the original
  graph and add the missing edges $(4,5)$, $(1,3)$ and $(2,4)$ with some weight
  \(W>1\).
- Once we reduce to the TSP, we conclude the presence of a Hamiltonian cycle if
  the optimal TSP tour has weight 6.
- Let \(W>1\) be the weight given to the missing edges that we will need to add
  back for the reduction to the TSP. The optimal TSP tour cost will be at least
  \(5+W\) if there is no Hamiltonian cycle.
