#+AUTHOR: Marcio Woitek
#+TITLE: Branch and Bound Solvers
#+DATE:
#+LATEX_HEADER: \usepackage[a4paper,left=1cm,right=1cm,top=1cm,bottom=1cm]{geometry}
#+LATEX_HEADER: \usepackage[american]{babel}
#+LATEX_HEADER: \usepackage[sc]{mathpazo}
#+LATEX_HEADER: \linespread{1.05}
#+LATEX_HEADER: \setlength\parindent{0pt}
#+OPTIONS: toc:nil
#+STARTUP: hideblocks

#+BEGIN_SRC latex
\thispagestyle{empty}
\pagestyle{empty}
#+END_SRC

* Problem 1
:PROPERTIES:
:UNNUMBERED: notoc
:END:

- If the LP relaxation at the "root" of the branch and bound is infeasible, the
  whole ILP must be infeasible.
- Each step of branch and bound solves the LP relaxation of some ILP problem
  that is either the original problem or obtained by branching.
- If the original ILP is unbounded, then the LP relaxation at the root of branch
  and bound (the very first LP we will solve) will be unbounded.

* Problem 2
:PROPERTIES:
:UNNUMBERED: notoc
:END:

- We may recursively solve two subproblems with the constraints $x_1 \leq 2$ and
  $x_1 \geq 3$, respectively.
- We recursively solve two subproblems with the constraints $x_4 \leq 6$ and
  $x_4 \geq 7$, respectively.

* Problem 3
:PROPERTIES:
:UNNUMBERED: notoc
:END:

- Suppose we solve an LP relaxation and find that the objective value is 8.5, we
  can prune this branch from further consideration.
- Suppose we solve an LP relaxation and find that the objective value is 9.8, we
  can prune this branch from further consideration.
- The optimal solution of the ILP will have objective value greater than or
  equal to 9.
